services:
  web:
    build: .
    image: shrike-umbrel
    restart: on-failure
    ports:
      - '6080:6080'
    volumes:
      - ${APP_DATA_DIR}/data:/root/.sparrow
    container_name: roman-shrike-wallet_web_1
